LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type               | Params | Mode
-----------------------------------------------------
0 | model | TimeConditionedMLP | 13.3 K | train
1 | path  | AffinePath         | 0      | train
-----------------------------------------------------
13.3 K    Trainable params
0         Non-trainable params
13.3 K    Total params
0.053     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode
/home/mathis/anaconda3/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:425: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
INFO:experiments.callback.progress:Training started
INFO:experiments.callback.progress:Epoch 0: loss 1.001e-01
INFO:experiments.callback.progress:Epoch 1: loss 9.520e-02
INFO:experiments.callback.progress:Epoch 2: loss 9.479e-02
`Trainer.fit` stopped: `max_epochs=3` reached.
INFO:experiments.callback.progress:Training done
INFO:matplotlib.animation:Animation.save using <class 'matplotlib.animation.HTMLWriter'>
INFO:matplotlib.animation:Animation.save using <class 'matplotlib.animation.HTMLWriter'>
Traceback (most recent call last):
  File "/home/mathis/anaconda3/lib/python3.12/site-packages/IPython/core/completerlib.py", line 130, in get_root_modules
    modules = rootmodules_cache[path]
              ~~~~~~~~~~~~~~~~~^^^^^^
KeyError: PosixPath('/home/mathis/Bureau/Stage - Code/StageTests/src')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mathis/anaconda3/lib/python3.12/site-packages/IPython/core/completer.py", line 3214, in _complete
    result = matcher(context)
             ^^^^^^^^^^^^^^^^
  File "/home/mathis/anaconda3/lib/python3.12/site-packages/IPython/core/completer.py", line 2750, in custom_completer_matcher
    matches = self.dispatch_custom_completer(context.token) or []
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathis/anaconda3/lib/python3.12/site-packages/IPython/core/completer.py", line 2790, in dispatch_custom_completer
    res = c(event)
          ^^^^^^^^
  File "/home/mathis/anaconda3/lib/python3.12/site-packages/IPython/core/completerlib.py", line 284, in module_completer
    return module_completion(event.line)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mathis/anaconda3/lib/python3.12/site-packages/IPython/core/completerlib.py", line 260, in module_completion
    return get_root_modules()
           ^^^^^^^^^^^^^^^^^^
  File "/home/mathis/anaconda3/lib/python3.12/site-packages/IPython/core/completerlib.py", line 132, in get_root_modules
    modules = module_list(path)
              ^^^^^^^^^^^^^^^^^
  File "/home/mathis/anaconda3/lib/python3.12/site-packages/IPython/core/completerlib.py", line 86, in module_list
    subdir = root[len(path)+1:]
                  ^^^^^^^^^
TypeError: object of type 'PosixPath' has no len()
